### PR TITLE
Adding date field to 'post detail' page and update 'about' page

### LINKED ISSUE #152: Adding date to the posts on 'post details'

### PR DESCRIPTION
**Pull request by Shoval-Ovadia**
- Post/templates/Post/post_detail.html  modified.
- pickATrip_django_apps/templates/pickATrip_django_apps/about.html modified.
- README.md modified.

closes #152

### CODE REVIEW

**Review by maayanhd — APPROVED** [review]

**Review by Leeadar — COMMENTED** [review]
Can you add a photo of how the ' post detail' page should look after the change?

**Comment by Shoval-Ovadia** [comment]
> Can you add a photo of how the ' post detail' page should look after the change?

image

**Review by Yarboa — APPROVED** [review]
LGTM

**Review by Leeadar — APPROVED** [review]
LGTM

**Pull request merged**
