### PR TITLE
Install flake8

### PR DESCRIPTION
**Pull request by shiraOs**
- Set up GitHub actions to run flake8 on the code as we submit
  new PRs.
- Create .github/workflows directory and the file flake8.yml
  inside.
- Update Pipfile files.

#15

### CODE REVIEW

**Review by nadavspinco — APPROVED** [review]

**Review by nadavspinco — APPROVED** [review]

**Review by EdDev — CHANGES_REQUESTED** [review]
Overall looks nice, I have two points that needs attention:
- Please squash the commits so we will see a single one with a proper commit message.
- In the commit message, please explain the reason for this change.

**Review by EdDev — APPROVED** [review]

**Comment by guy9050** [comment]
Please make flake8 checks run on this pr

**Review by nadavspinco — APPROVED** [review]

**Review by AmirMiller91 — COMMENTED** [review]
I tested the functionality of flake8 on my fork in the following way:
1. Created a pull request from this PR into my fork main branch.
2. Created a local branch based on the fetched origin/main.
3. Created a dummy text file and committed it to the local branch.
4. Pushed the branch to my fork and created a local PR.
5. Merged the branch with my fork main.

The result of the test is that the flake8 tool runs but rejects the PR due to unconforming Python files for Django. I will create a new Issue to fix that --> created, issue #24.

Other than that, this PR can be merged after a RedHatter approves the commit message (was it altered?).

For reference, this is the output of the test:

flake8

**Comment by nadavspinco** [comment]
> Please make flake8 checks run on this pr
 @guy9050 
I don't know why flake8 doesn't run on this PR because when I tried to merge it to my main repository it worked.

**Comment by AmirMiller91** [comment]
@nadavspinco For me, when I opened the PR to my fork from shiraOs:install-flake8, the flake8 tests did NOT run. Only when I added a new PR did the test ran.

**Comment by EdDev** [comment]
OK, so it works like this: The action will work only if there is a workflow set in the target branch (main) or if a PR is created from within the repo itself (but we do not work this way).

See ref: https://github.com/beyond-io/picATrip/pull/26

I'm fine with taking this one and you sending a fix later, it will show the CI on action.

**Pull request merged**
