### PR TITLE
Add Url tests for Homepage,about

### PR DESCRIPTION
**Pull request by nadavspinco**
based on

### CODE REVIEW

**Review by maayanhd — APPROVED** [review]
Consider adding tests for the objects sent to the views of the commenting page and the postList page, and after you'll add post objects to the homepage either for it, but that's for later

**Review by Yarboa — APPROVED** [review]

**Comment by Yarboa** [comment]
> Consider adding tests for the objects sent to the views of the commenting page and the postList page, and after you'll add post objects to the homepage either for it, but that's for later

+1 @nadavspinco Can you think of additional tests?

**Comment by nadavspinco** [comment]
> > Consider adding tests for the objects sent to the views of the commenting page and the postList page, and after you'll add post objects to the homepage either for it, but that's for later
> 
> +1 @nadavspinco Can you think of additional tests?

I added URL tests for all URLs on our site, I will add later client tests but those are different kinds of tests.

**Review by maayanhd — COMMENTED** [review]
Are you writing the tests on a tests folder to avoid collision with tests.py files? And other than that, please add tests for the assertion of the actual objects sent to the HTML pages through the view, I think Barak said something about it, maybe assuring that a post object and a Queryset (I think) of comments is sent to post detail, for example, look at the views.py to see what objects are sent. I think it can be a good addition. I understand you planned on doint it on a different PR, just wanted to give further explanations.

**Review by maayanhd — APPROVED** [review]

**Pull request merged**
