### PR TITLE
Navbar icons

### PR DESCRIPTION
**Pull request by nadavspinco**
Replace navbar logo 
add navbar icons,change background color
image
 
image

### CODE REVIEW

**Review by maayanhd — CHANGES_REQUESTED** [review]
image
I don't see the app icon and also you haven't done rebase with the last PR (the post detail page styling)

**Comment by nadavspinco** [comment]
> image
> I don't see the app icon and also you haven't done rebase with the last PR (the post detail page styling)
@maayanhd 
Try to do vagrant destroy and then let me know if this problem is happening.
(Vagrant provision is not enough for collecting static files)

**Comment by maayanhd** [comment]
@nadavspinco I forgot to delete the DB now it's working..

**Review by maayanhd — APPROVED** [review]
LGTM

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
