### PR TITLE
Create a bootstrap script to install Pipenv

### LINKED ISSUE #7: Create a bootstrap script to automate environment setup
The script should run automatically on the VM using the Vagrant provisioning process.
Initially, the script should only install Pipenv and tell it to install software dependencies.

### PR DESCRIPTION
**Pull request by AmirMiller91**
Automating the installation of Pipenv on the Vagrant box (Closes #7).

IMPORTANT: this PR is based on PR #2
Once it is merged, this PR will need to be rebased before it can be merged.

### CODE REVIEW

**Review by Yarboa — COMMENTED** [review]
Please add a link to Issue#number

**Comment by AmirMiller91** [comment]
I already posted a question asking how to do that to the beyond-05 channel, but none of the red hatters replied yet. Ma'ayan from our team replied, saying that I can link the issue number by mentioning it at the end of the message. I did mention the issue number (albeit at the beginning) but this did not seem to work.

**Comment by maayanhd** [comment]
you can look at the comment of Edward on my PR (it explains how to link automatically), but you're right, the first thing I suggested didn't ultimately worked.

**Comment by AmirMiller91** [comment]
I edited the PR message to use the "closes" keyword for linking a PR to an issue. I tried both capitalized and lower case, but it doesn't change the number attached to the PR.

**Comment by Yarboa** [comment]
> I edited the PR message to use the "closes" keyword for linking a PR to an issue. I tried both capitalized and lower case, but it doesn't change the number attached to the PR.

Did you commit --amend and git push again?

**Comment by Yarboa** [comment]
Looks good to me

**Pull request merged**
