### PR TITLE
Add navbar-logo

### PR DESCRIPTION
**Pull request by nadavspinco**
add navbar-logo.png to static/pickATrip_django_apps
use django static to inculde the image file

### CODE REVIEW

**Review by maayanhd — APPROVED** [review]

**Comment by maayanhd** [comment]
maybe just open a small issue and link this PR to it.

**Review by Yarboa — APPROVED** [review]

**Review by Leeadar — COMMENTED** [review]
Maybe you can add the logo photo to the 'media' folder that we have?

**Comment by nadavspinco** [comment]
> Maybe you can add the logo photo to the 'media' folder that we have?

If I want to use the Django static option I think I have to use a pickATrip_django_apps\static\pickATrip_django_apps path.

**Review by Shoval-Ovadia — APPROVED** [review]

**Review by guy9050 — APPROVED** [review]
LGTM

**Pull request merged**
