### PR TITLE
Adding a Vagrantfile for spinning up a development VM

### LINKED ISSUE #1: Create a Vagrantfile
The way Vagrant works is that we create a file called Vagrantfile that contains the
instructions about how to create and bring up a virtual machine (VM) for working on our project.

We want to make sure that all the teammates can successfully use Git to clone the team project and Vagrant to bring up the development environment on their machines.

### PR DESCRIPTION
**Pull request by Leeadar**
Vagrant is a tool for using virtual machines to share development
environments.
Learn more about it at:
https://www.vagrantup.com/
Also making changes to the `.gitignore` file to ignore so data that
Vagrant creates.

closes : #1

### CODE REVIEW

**Review by Yarboa — COMMENTED** [review]
Consider Adding Into readme
That application is running in vagrant environemnt

**Comment by Leeadar** [comment]
Do I need to change the README.md file in this PR? Or should I add this review to the "Updating ReadMe file" PR to avoid conflicts?

**Review by maayanhd — APPROVED** [review]
Looks fine to me, referring to mentioning the use of the vagrant technology in the ReadMe file, it will be fixed shortly as mentioned in issue #11

**Comment by Yarboa** [comment]
> Do I need to change the README.md file in this PR? Or should I add this review to the "Updating ReadMe file" PR to avoid conflicts?

Ahmm ok, tend to agree, you could create an Issue, to add it once the README PR is merged

**Comment by Leeadar** [comment]
So this PR can be merged? @Yarboa

**Comment by Yarboa** [comment]
> So this PR can be merged? @Yarboa

Please Add in reply here the Issue#nubmer

**Review by Shoval-Ovadia — COMMENTED** [review]
It looks good to me.

**Comment by Leeadar** [comment]
In issue #11 is written "adding technologies used for development". Do you mean that we need to add this issue the comment: "Adding Into readme that application is running in vagrant environment", or should I need to create a new issue?

**Comment by Yarboa** [comment]
Looks Good to me

**Pull request merged**
