### PR TITLE
Updating navbar logo

### LINKED ISSUE #105: Updating navbar-logo

### PR DESCRIPTION
**Pull request by Leeadar**
- Removing the white square behind the logo

**Before:**
image

**After:**
image

closes #105

### CODE REVIEW

**Comment by maayanhd** [comment]
Do we really need this PR if we use a picture with a white background on a white background? maybe if we add some color or redesign the background it will be needed, this is what I think, but I'm open to debate it.

**Comment by Leeadar** [comment]
@maayanhd We talked about this and decided it is looks better that way. At least for meantime, I think it is looking more natural.

**Review by maayanhd — APPROVED** [review]
Now I see the difference, I couldn't see it before.

**Review by nadavspinco — CHANGES_REQUESTED** [review]
I suggest we will try to make the logo smaller because the navbar looks thick.

**Review by Yarboa — APPROVED** [review]

**Pull request merged**
