### PR TITLE
Fix content overflow bug

### LINKED ISSUE #70: Fixing html page fitting with navigation bar
The scrolling bar doesn't work for some HTML pages- need to be fixed (**low priority**) - look for about.html in PR #67

### PR DESCRIPTION
**Pull request by nadavspinco**
remove footer position fixed
set content and footer min hight

closes #70

### CODE REVIEW

**Review by maayanhd — APPROVED** [review]

**Review by Yarboa — APPROVED** [review]

**Review by Leeadar — APPROVED** [review]
LGTM

**Review by Shoval-Ovadia — APPROVED** [review]

**Review by guy9050 — APPROVED** [review]
LGTM

**Comment by Yarboa** [comment]
@nadavspinco Please rebase

**Comment by nadavspinco** [comment]
> @nadavspinco Please rebase

Done.

**Comment by nadavspinco** [comment]
> @nadavspinco Please rebase

@Yarboa Done.

**Comment by Yarboa** [comment]
+2, LGTMT

**Pull request merged**
