### PR TITLE
Updating forms visibility

### LINKED ISSUE #140: Updating forms visibility
Change the width of form elements

### PR DESCRIPTION
**Pull request by Leeadar**
- Updating profile page
- Spacing between form fields
- Change the width of form elements

New profile page:

image

closes #140

### CODE REVIEW

**Review by maayanhd — APPROVED** [review]
LGTM, also we discussed this manner offline, so..

**Review by nadavspinco — APPROVED** [review]
LGTM

**Review by Shoval-Ovadia — APPROVED** [review]
LGTM

**Review by guy9050 — APPROVED** [review]
lgtm

**Pull request merged**
